// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/Background.vue')['default']
    Galaxy: typeof import('./src/components/Galaxy.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    ListBlogs: typeof import('./src/components/ListBlogs.vue')['default']
    ListChallenges: typeof import('./src/components/ListChallenges.vue')['default']
    ListProjects: typeof import('./src/components/ListProjects.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SolarSystem: typeof import('./src/components/SolarSystem.vue')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    WrapLanguage: typeof import('./src/components/WrapLanguage.vue')['default']
  }
}
