/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/Background.vue')['default']
    Galaxy: typeof import('./src/components/Galaxy.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    ListBlogs: typeof import('./src/components/ListBlogs.vue')['default']
    ListChallenges: typeof import('./src/components/ListChallenges.vue')['default']
    ListProjects: typeof import('./src/components/ListProjects.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sakana: typeof import('./src/components/Sakana.vue')['default']
    SolarSystem: typeof import('./src/components/SolarSystem.vue')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    WrapLanguage: typeof import('./src/components/WrapLanguage.vue')['default']
  }
}
