/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./src/components/AppLink.vue')['default']
    Background: typeof import('./src/components/background/index.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Galaxy: typeof import('./src/components/background/Galaxy.vue')['default']
    ListChallenges: typeof import('./src/components/ListChallenges.vue')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sakana: typeof import('./src/components/background/Sakana.vue')['default']
    ShikiMagicMoveDemo: typeof import('./src/components/shiki/ShikiMagicMoveDemo.vue')['default']
    ShikiMagicMoveMatch: typeof import('./src/components/shiki/ShikiMagicMoveMatch.vue')['default']
    SolarSystem: typeof import('./src/components/background/SolarSystem.vue')['default']
    StreamAnnouncement: typeof import('./src/components/StreamAnnouncement.vue')['default']
    SubNav: typeof import('./src/components/SubNav.vue')['default']
    TextCopy: typeof import('./src/components/TextCopy.vue')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    WrapperPost: typeof import('./src/components/WrapperPost.vue')['default']
    YouTubeEmbed: typeof import('./src/components/YouTubeEmbed.vue')['default']
  }
}
