// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Background: typeof import('./components/Background.vue')['default']
    Galaxy: typeof import('./components/Galaxy.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SolarSystem: typeof import('./components/SolarSystem.vue')['default']
    ToggleTheme: typeof import('./components/ToggleTheme.vue')['default']
  }
}

export {}
